version: '3'
services:
  web-server:
    platform: linux/x86_64
    # platform: linux/arm64/v8
    image: web-server:v0.1
    environment:
      - SERVER_DOMAIN=http://chatgpt-server:8000
#      - NUXT_PUBLIC_APP_NAME='ChatGPT UI' # The name of the application
#      - NUXT_PUBLIC_TYPEWRITER=true # Whether to enable the typewriter effect, default false
#      - NUXT_PUBLIC_TYPEWRITER_DELAY=50 # The delay time of the typewriter effect, default 50ms
    depends_on:
      - chatgpt-server
    ports:
      - '${WEB_PORT:-3000}:3000'
    networks:
      - chatgpt_network
    restart: always
  chatgpt-server:
    platform: linux/x86_64
    # platform: linux/arm64/v8
    image: chatgpt-server:v0.1
    environment:
      - APP_DOMAIN=${APP_DOMAIN:-localhost:9000}
      - SERVER_WORKERS=4 # The number of worker processes for handling requests.
      - DB_URL=${DB_URL:-sqlite:///db.sqlite3}
      # - DB_URL=postgres://postgres:postgrespw@localhost:49153/chatgpt # If this parameter is not set, the built-in Sqlite will be used by default. It should be noted that if you do not connect to an external database, the data will be lost after the container is destroyed.
      - ACCOUNT_EMAIL_VERIFICATION=${ACCOUNT_EMAIL_VERIFICATION:-none} # Determines the e-mail verification method during signup – choose one of "none", "optional", or "mandatory". Default is "optional". If you don't need to verify the email, you can set it to "none".
      # If you want to use the email verification function, you need to configure the following parameters
#      - EMAIL_HOST=SMTP server address
#      - EMAIL_PORT=SMTP server port
#      - EMAIL_HOST_USER=
#      - EMAIL_HOST_PASSWORD=
#      - EMAIL_USE_TLS=True
#      - EMAIL_FROM=no-reply@example.com  #Default sender email address
    ports:
      - '${CHATGPT_PORT:-8000}:8000'
    networks:
      - chatgpt_network
    restart: always
  nginx-server:
    platform: linux/x86_64
    # platform: linux/arm64/v8
    image: nginx-server:v0.1
    # environment:
      # - BACKEND_URL=http://web-server:3000
    ports:
      - '${NGINX_PORT:-80}:80'
    depends_on:
      - web-server
      - chatgpt-server
    networks:
      - chatgpt_network
    restart: always

networks:
  chatgpt_network:
    driver: bridge
