# Generated by Django 4.1.7 on 2023-04-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_conversation_model_name_conversation_total_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='billing_rule',
            field=models.FloatField(choices=[(0.003, 'TENOPENAI'), (0.0003, 'OPENAI')], default=0.003),
        ),
    ]
