# Generated by Django 4.1.7 on 2023-02-22 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0010_add_converstaion_total_token_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='Conversation',
            name='model_name',
            field=models.CharField(max_length=255),
        ),
    ]

